apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORT
              value: "7097"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: HarmonyTeamsSecretKey
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/harmony.pfx
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: AppEndpointConfiguration__AutomationEndpoint
              value: https://harmony.automations:443/
            - name: BrokerConfiguration__Host
              value: harmony-rabbitmq
            - name: ConnectionStrings__HarmonyConnection
              value: Server=harmony-sql-server;database=harmony;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          image: harmony-api:latest
          imagePullPolicy: IfNotPresent
          name: harmony-api
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /https/harmony.pfx
              subPath: harmony.pfx
              name: cert-config-map
      restartPolicy: Always
      volumes:
        - name: cert-config-map
          configMap:
            name: cert-config-map
