apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: harmony-gateway
spec:
  type: LoadBalancer
  ports:
    - name: "7108"
      port: 7108
      targetPort: 443
  selector:
    app: api-gateway
