apiVersion: v1
kind: Service
metadata:
  labels:
    app: automations
  name: harmony-automations
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    app: automations
