apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORT
              value: "7096"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: HarmonyTeamsSecretKey
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/harmony.pfx
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
          image: harmony-client:latest
          imagePullPolicy: IfNotPresent
          name: harmony-client
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /https/harmony.pfx
              subPath: harmony.pfx
              name: cert-config-map
      restartPolicy: Always
      volumes:
        - name: cert-config-map
          configMap:
            name: cert-config-map
