apiVersion: v1
kind: Service
metadata:
  labels:
    app: client
  name: harmony-client
spec:
  type: LoadBalancer
  ports:
    - name: "7096"
      port: 7096
      targetPort: 80
  selector:
    app: client
