apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTPS_PORT
              value: "7121"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: HarmonyTeamsSecretKey
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/harmony.pfx
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: AppEndpointConfiguration__HarmonyApiEndpoint
              value: https://harmony-api:443/
            - name: BrokerConfiguration__Host
              value: harmony-rabbitmq
            - name: ConnectionStrings__HarmonyJobsConnection
              value: Server=harmony-sql-server;database=Harmony.Notifications.Jobs;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          image: harmony-notifications:latest
          imagePullPolicy: IfNotPresent
          name: harmony-notifications
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /https/harmony.pfx
              subPath: harmony.pfx
              name: cert-config-map
      restartPolicy: Always
      volumes:
        - name: cert-config-map
          configMap:
            name: cert-config-map
