apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: harmony-notifications
spec:
  ports:
    - name: "7121"
      port: 7121
      targetPort: 443
  selector:
    app: notifications
