version: "3.9"
services:
   api:
    build: 
        context: .
        dockerfile: src/Services/Harmony.Api/Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony-api
    ports:
        - "7097:443"
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7097
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx 
        - ConnectionStrings__HarmonyConnection=Server=harmony-sql-server;database=harmony;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
        - AppEndpointConfiguration__AutomationEndpoint=https://harmony.automations:443/
        - BrokerConfiguration__Host=harmony-rabbitmq
        - ElasticConfiguration:Uri=http://elasticsearch:9200
    volumes:
        - $USERPROFILE/.aspnet/https:/https/
    depends_on:
        - sql_server
        - rabbitmq
   automations:
    build: 
        context: .
        dockerfile: src/Services/Harmony.Automations/Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony-automations
    ports:
        - "7277:443"
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7277
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx
        - AppEndpointConfiguration__HarmonyApiEndpoint=https://harmony.api:443/
        - BrokerConfiguration__Host=harmony-rabbitmq 
        - ConnectionStrings__HarmonyJobsConnection=Server=harmony-sql-server;database=Harmony.Automations.Jobs;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
        - MongoDB__ConnectionURI=mongodb://harmony-mongodb-server:27017
        - ElasticConfiguration:Uri=http://elasticsearch:9200
    volumes:
        - $USERPROFILE/.aspnet/https:/https/
    depends_on:
        - sql_server
        - rabbitmq
        - mongodb
   notifications:
    build: 
        context: .
        dockerfile: src/Services/Harmony.Notifications/Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony-notifications
    ports:
        - "7121:443"
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7121
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx
        - AppEndpointConfiguration__HarmonyApiEndpoint=https://harmony.api:443/
        - BrokerConfiguration__Host=harmony-rabbitmq 
        - ConnectionStrings__HarmonyJobsConnection=Server=harmony-sql-server;database=Harmony.Notifications.Jobs;User Id=sa;Password=%HarmonyTeams100;TrustServerCertificate=True
        - ElasticConfiguration:Uri=http://elasticsearch:9200
    volumes:
        - $USERPROFILE/.aspnet/https:/https/
    depends_on:
        - sql_server
        - rabbitmq
   signalr:
    build: 
        context: .
        dockerfile: src/Services/Harmony.SignalR/Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony-signalr
    ports:
        - "7262:443"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7262
        - BrokerConfiguration__Host=harmony-rabbitmq
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx
        - ElasticConfiguration:Uri=http://elasticsearch:9200
    volumes:
        - $USERPROFILE/.aspnet/https:/https/
    depends_on:
        - rabbitmq
   client:
    build: 
        context: .
        dockerfile: src/Web/Harmony.Client/Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony-client
    ports:
        - "7096:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7096
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx 
    volumes:
        - $USERPROFILE/.aspnet/https:/https/
    depends_on:
        - signalr
        - api
        - api_gateway
   api_gateway:
    build: 
        context: .
        dockerfile: src/ApiGateways/Harmony.ApiGateway/Dockerfile
        args:
          BUILD_CONFIGURATION: Debug
    container_name: harmony-apigateway
    ports:
        - "7108:443"
    restart: always
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=7108
        - ASPNETCORE_Kestrel__Certificates__Default__Password=HarmonyTeamsSecretKey 
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/harmony.pfx 
    volumes:
        - $USERPROFILE/.aspnet/https:/https/
   elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
   kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 
   rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: harmony-rabbitmq
   sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: harmony-sql-server
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=%HarmonyTeams100
   mongodb:
    image: mongo:latest
    container_name: harmony-mongodb-server
